name: routine
description: An app with habit tracker, task management, mood tracker, and many more features for Android, Web, and Windows.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  permission_handler: ^10.2.0
  fluttertoast: ^8.1.1
  app_settings: ^5.1.1
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_app_name:
  name: "Routine"

flutter_native_splash:
  color: "#F9F9F7"
  image: assets/images/icon.png
  color_dark: "#202020"
  android: true
  ios: false
  android_12:
    image: assets/images/icon.png
    icon_background_color: "#F9F9F7"
    icon_background_color_dark: "#202020"

flutter_launcher_icons:
  ios: false
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/svgs/1.svg
    - assets/svgs/2.svg
    - assets/svgs/3.svg
    - assets/svgs/4.svg
    - assets/svgs/5.svg
    - assets/svgs/habit.svg
    - assets/svgs/privacy.svg
    - assets/svgs/routine.svg
    - assets/svgs/task.svg
    - assets/svgs/notification.svg
    - assets/svgs/storage.svg
    - assets/svgs/1_dark.svg
    - assets/svgs/2_dark.svg
    - assets/svgs/3_dark.svg
    - assets/svgs/4_dark.svg
    - assets/svgs/5_dark.svg
    - assets/svgs/habit_dark.svg
    - assets/svgs/privacy_dark.svg
    - assets/svgs/routine_dark.svg
    - assets/svgs/task_dark.svg
    - assets/svgs/notification_dark.svg
    - assets/svgs/storage_dark.svg
